# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.30.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.30.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/maceo/gnosis/retesteth

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/maceo/gnosis/retesteth

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.30.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/maceo/gnosis/retesteth/CMakeFiles /Users/maceo/gnosis/retesteth//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/maceo/gnosis/retesteth/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named secp256k1

# Build rule for target.
secp256k1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 secp256k1
.PHONY : secp256k1

# fast build rule for target.
secp256k1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/secp256k1.dir/build.make CMakeFiles/secp256k1.dir/build
.PHONY : secp256k1/fast

#=============================================================================
# Target rules for targets named BuildInfo.h

# Build rule for target.
BuildInfo.h: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BuildInfo.h
.PHONY : BuildInfo.h

# fast build rule for target.
BuildInfo.h/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuildInfo.h.dir/build.make CMakeFiles/BuildInfo.h.dir/build
.PHONY : BuildInfo.h/fast

#=============================================================================
# Target rules for targets named devcore

# Build rule for target.
devcore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 devcore
.PHONY : devcore

# fast build rule for target.
devcore/fast:
	$(MAKE) $(MAKESILENT) -f libdevcore/CMakeFiles/devcore.dir/build.make libdevcore/CMakeFiles/devcore.dir/build
.PHONY : devcore/fast

#=============================================================================
# Target rules for targets named devcrypto

# Build rule for target.
devcrypto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 devcrypto
.PHONY : devcrypto

# fast build rule for target.
devcrypto/fast:
	$(MAKE) $(MAKESILENT) -f libdevcrypto/CMakeFiles/devcrypto.dir/build.make libdevcrypto/CMakeFiles/devcrypto.dir/build
.PHONY : devcrypto/fast

#=============================================================================
# Target rules for targets named dataobj

# Build rule for target.
dataobj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dataobj
.PHONY : dataobj

# fast build rule for target.
dataobj/fast:
	$(MAKE) $(MAKESILENT) -f libdataobj/CMakeFiles/dataobj.dir/build.make libdataobj/CMakeFiles/dataobj.dir/build
.PHONY : dataobj/fast

#=============================================================================
# Target rules for targets named hunter_upload_cache

# Build rule for target.
hunter_upload_cache: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hunter_upload_cache
.PHONY : hunter_upload_cache

# fast build rule for target.
hunter_upload_cache/fast:
	$(MAKE) $(MAKESILENT) -f retesteth/CMakeFiles/hunter_upload_cache.dir/build.make retesteth/CMakeFiles/hunter_upload_cache.dir/build
.PHONY : hunter_upload_cache/fast

#=============================================================================
# Target rules for targets named retesteth

# Build rule for target.
retesteth: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 retesteth
.PHONY : retesteth

# fast build rule for target.
retesteth/fast:
	$(MAKE) $(MAKESILENT) -f retesteth/CMakeFiles/retesteth.dir/build.make retesteth/CMakeFiles/retesteth.dir/build
.PHONY : retesteth/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BuildInfo.h"
	@echo "... hunter_upload_cache"
	@echo "... secp256k1"
	@echo "... dataobj"
	@echo "... devcore"
	@echo "... devcrypto"
	@echo "... retesteth"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

